#!/bin/zsh -e

S=t_src
D=_t_dest

prepare()
{
    local t=$1
    mkdir -p ./$D
    mkdir -p ./$D/$t
    rm -f ./$D/${t}.log    
    rm -f ./$D/${t}.zsh.log
    rm -rf ./$D/$t/*(N)
}


run0()
{
    local src=$1
    local dest=$2

    SRPMIX7_XCMD_DIR=./xcmd ./srpmix7 expand --stype file --sloc $src --dtype dir --dloc $dest
}

run()
{
    local s=${1##*/}
    local t=${s//./-}
    local v=${2}

    prepare "$t"


    =printf "%45s -> %-45s: " ${S}/$s ./$D/$t

    if run0 ${S}/$s ./$D/$t > ./$D/${t}.log 2>&1; then
	if [[ -f $v ]]; then
	    if zsh $v ./$D/$t > ./$D/${t}.zsh.log 2>&1; then
		echo "passed(expand+extra)"
		return 0
	    else
		echo "ERROR (extra check with $v)"
	    fi
	else
	    echo "passed(expand)"
	    return 0
	fi
    else
	case $status in
	    (1) echo "ERROR (prepare,BUG?)"
		return 1;;
	    (2) echo "error (expand)"
		return 2;;
	esac
    fi
}

main()
{
    local tmp
    local ext
    local c=0

    for ext in .src.rpm; do
	for tmp in ${S}/*${ext}; do
	    if ! run $tmp ${tmp%${ext}}.zsh; then
		c=1
	    fi
	done
    done

    return $c
}

main
